### ISSUE TITLE
Configuring integration for device crashes WebSocket API - message 257:None is not str

### ISSUE THREAD

**Issue by samyun** [ryanwinter/hass-rainforest-emu-2#16]
Howdy, 

I have my EMU-2 connected via USB to a PC running Proxmox, passthroughed to the HA image VM. After installing this integration in HACS, I saw it was automatically detected, to `/dev/ttyACM0 - RFA-Z105-2 HW2.7.3 EMU-2 - Rainforest Automation, Inc.`. 

When I click "Configure", it errors out and the Home Assistant API crashed, so the supervisor watchdog reboots it. 

KVMing into the VM console, and running `supervisor logs` with the Debug logging level, I see this: 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/4411707/172019936-b13da638-ed23-446b-afbf-91b873e5212b.png">

It seems that "something" in the integration during configuration is throwing some exception, causing the API to crash. 

I'm not very familiar at all with HA internals, so I'd appreciate if anyone could provide some tips on debugging this further. A stack trace itself would go a long way :)

**Comment by ryanwinter** [comment]
Hi @samyun,

The main branch has a bug which might be what you are hitting into. What version of the integration are you running?

**Comment by samyun** [comment]
The integration version is v1.2.0.

**Comment by samyun** [comment]
Still happening with main

**Comment by samyun** [comment]
Alright - so I figured out some of the issue - I'll send out a PR shortly with the fix for auto configuration. However, it seems that something during the flow causes an issue, causing "something" to die, which causes Home Assistant entirely to die, until the watchdog reboots it. The original issue I had been running into seems to be caused by the config not being saved until AFTER whatever "this" was, so when the watchdog brought HA back up, I needed to start all over. "Something" I did made it so that it saved the config, and when it came up, the config was saved and everything started working again. 

Here are the logs that seem to be the cause of the websocket crashing - I don't know if this means anything to you, and whether or not this sounds familiar enough for you to figure out what happened. 

```
2022-07-17 22:41:36 INFO (MainThread) [custom_components.rainforest_emu_2.emu2] Starting serial_read loop
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 21: <InstantaneousDemand>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 45: <DeviceMacId>REDACTED</DeviceMacId>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 43: <MeterMacId>REDACTED</MeterMacId>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 33: <TimeStamp>0x2a67af17</TimeStamp>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 25: <Demand>0x00188d</Demand>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 35: <Multiplier>0x00000003</Multiplier>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 29: <Divisor>0x00001388</Divisor>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 31: <DigitsRight>0x03</DigitsRight>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 29: <DigitsLeft>0x05</DigitsLeft>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 44: <SuppressLeadingZero>Y</SuppressLeadingZero>
2022-07-17 22:41:43 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] received 22: </InstantaneousDemand>
2022-07-17 22:41:44 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] XML write b'<Command><Name>get_device_info</Name></Command>'
2022-07-17 22:41:47 DEBUG (MainThread) [custom_components.rainforest_emu_2.config_flow] Cancelled, caught 
2022-07-17 22:45:49 INFO (Thread-7 (_run)) [google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager] Observed non-terminating stream error 503 The service was unable to fulfill your request. Please try again. [code=8a75]
2022-07-17 22:45:49 INFO (Thread-7 (_run)) [google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager] Observed recoverable stream error 503 The service was unable to fulfill your request. Please try again. [code=8a75]
2022-07-17 22:45:49 WARNING (Thread-3 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (7)
2022-07-17 22:45:49 INFO (Thread-7 (_run)) [google.api_core.bidi] Re-established stream
2022-07-17 22:45:49 INFO (Thread-ConsumeBidirectionalStream) [google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager] Observed non-terminating stream error 503 The service was unable to fulfill your request. Please try again. [code=8a75]
2022-07-17 22:45:49 INFO (Thread-ConsumeBidirectionalStream) [google.cloud.pubsub_v1.subscriber._protocol.streaming_pull_manager] Observed recoverable stream error 503 The service was unable to fulfill your request. Please try again. [code=8a75]
2022-07-17 22:45:55 INFO (Thread-3 (_thread_main)) [homeassistant.components.mqtt.client] Connected to MQTT server core-mosquitto:1883 (0)
2022-07-17 22:46:19 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] Requesting data <class 'custom_components.rainforest_emu_2.emu2_entities.DeviceInfo'>
2022-07-17 22:46:19 DEBUG (MainThread) [custom_components.rainforest_emu_2.config_flow] get_devices_properties DeviceInfo response is None
2022-07-17 22:46:19 DEBUG (MainThread) [custom_components.rainforest_emu_2.emu2] Requesting data <class 'custom_components.rainforest_emu_2.emu2_entities.InstantaneousDemand'>
2022-07-17 22:46:19 DEBUG (MainThread) [custom_components.rainforest_emu_2] path: '/dev/serial/by-id/usb-Rainforest_Automation__Inc._RFA-Z105-2_HW2.7.3_EMU-2-if00', host:'None', port:'None
2022-07-17 22:46:19 INFO (MainThread) [custom_components.rainforest_emu_2.emu2] Starting serial_read loop
2022-07-17 22:46:19 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.rainforest_emu_2
2022-07-17 22:46:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2022-07-17 22:46:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2022-07-17 22:46:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 676, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 653, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by ryanwinter** [comment]
Thanks for the PR! I was meaning to fix this but just havent had time to get around to it.
