### ISSUE TITLE
EMU-2 will stop working in 2023.3

### ISSUE THREAD

**Issue by monsieurlatte** [ryanwinter/hass-rainforest-emu-2#28]
Just in case others haven't seen it, in the logs it shows.

2023-02-23 12:09:14.252 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for rainforest_emu_2 using this method at custom_components/rainforest_emu_2/__init__.py, line 44: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by ryanwinter** [comment]
Let me take a look at this. What version of home assistant are you running? Cause I dont see that warning.

**Comment by ryanwinter** [comment]
Never mind, I see it when installing

**Comment by monsieurlatte** [comment]
started seeing it in early Home Assistant 2023.2.x and am seeing it now still on Home Assistant 2023.2.5.   here is the full log snippet


2023-02-23 13:23:02.394 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for balboa using this method at custom_components/balboa/__init__.py, line 52: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by monsieurlatte** [comment]
Installed 1.3.1 and it's erroring when starting up the entity, even though it's plugged in, rolling back to 1.2.0 and it's working again.  only because I have no idea how to code, another repo I worked with had to make the same changes for async and this what they did for changes if that helps you at all. https://github.com/garbled1/balboa_homeassistan/commit/aba08ca7193834c858aa7acb144f5b374ba8a16c

**Comment by zSprawl** [comment]
I got the following error after applying the latest update:

`2023-02-26 21:08:35.618 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Rainforest EMU-2 for rainforest_emu_2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/rainforest_emu_2/__init__.py", line 38, in async_setup_entry
emu2device = RainforestEmu2Device(hass, entry.data)
File "/config/custom_components/rainforest_emu_2/__init__.py", line 80, in __init__
self._emu2 = Emu2(properties[ATTR_DEVICE_PATH], properties[CONF_HOST], properties[CONF_PORT])
KeyError: 'host' `

Since I had a VM snapshot handy, I went ahead and deleted the device integration and adding it back. It took without issue and all the sensors came back online with no data loss.

**Comment by monsieurlatte** [comment]
Does it work if you update to the latest vesion of the build and then delete the device and add it back in?

**Comment by ryanwinter** [comment]
This should be fixed in 1.3.2

**Comment by monsieurlatte** [comment]
Can confirm the fix is working!!  Thank you so much!
