### ISSUE TITLE
Cannot add TCP connection

### ISSUE THREAD

**Issue by widewing** [ryanwinter/hass-rainforest-emu-2#32]
I plan to use ser2net to forward EMU-2 connection. 
When connect directly via serial port, it works flawlessly. After setting up ser2net (and tested by netcat successfully), I tried to configure the HA with TCP, but it failed with unknown error:
![image](https://github.com/ryanwinter/hass-rainforest-emu-2/assets/4755389/cbf22ea6-98f7-4df1-9a88-354fc4fe1a64)
In HA log, it's showing:
```
2023-07-03 21:19:09.050 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 395, in _async_handle_step
    result = await self.async_finish_flow(flow, result.copy())
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 926, in async_finish_flow
    title=result["title"],
KeyError: 'title'
```
It appears this integration is handling names incorrectly when using TCP?

**Comment by posicat** [comment]
I'm getting the same error on my install.  ser2net is working just fine.

**Comment by posicat** [comment]
There's a PR out there that hasn't been merged in yet that fixes the error
https://github.com/ryanwinter/hass-rainforest-emu-2/pull/33/files

It's a one-line change, I went in and made it manually, and it works now!
